### ISSUE TITLE
Update README with instructions, arch diagram and other info

### ISSUE THREAD

**Issue by rvennam** [ibm-watson-iot/iot-cognitive-samples#2]
Just saw the great blog post about this sample:
http://linkis.com/developer.ibm.com/re/R8u3T

Please update the README with similar content so that this can be a featured repository.

**Comment by durera** [comment]
Updated README based on tutorial from devworks: https://github.com/ibm-watson-iot/iot-cognitive-samples/commit/29fcf278ee5936737a087d530700a869f4dd17e7
